---

- hosts: all
  become: true
  tasks:
  
  - name: update repository index
    yum:
      update_cache: yes

  - name: remove httpd pachage
    yum:
      name: httpd
      state: absent
  
  - name: remove php
    yum:
      name: php
      state: absent
