---


- hosts: all
  become: true
  tasks:
  
  - name: install updates
    tags: always,CentoOS
    yum:
      update_only: yes
      update_cache: yes

- hosts: web_servers
  become: true
  tasks:
  
  - name: install httpd and php packages
    tags: httpd,php,CentOS,web
    package:
      name: 
        - httpd
        - php
      state: latest
      
- hosts: db_servers
  become: true
  tasks:
  
  - name: insatll mariadb
    tags: mariadb,CentOS,db
    yum:
      name: mariadb.x86_64
      state: latest
